name: abeautifulmistake
favicon: null
layout_spectrum: 0.9910395
typography_spectrum: 0.6845878
title: a beautiful mistake
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7e2f5'
    - '#0d2d2d'
    - '#6a602a'
    - '#b3a8a6'
    - '#e9412e'
  brandStrength: 0.9375
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
