name: abeautifulmistake
favicon: null
layout_spectrum: 0.9910395
typography_spectrum: 0.6845878
title: a beautiful mistake
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C5C5C7'
    - '#7F8187'
    - '#26373B'
    - '#000205'
  brandStrength: 0.8046595
  lightness: 0.7759857
  saturation: 0.2114142
  rhythmicContrast: 0.8530466
purpose: []
